### ISSUE TITLE
Calling Formula.sha1 is disabled! Use Formula.sha256 instead.

### ISSUE THREAD

**Issue by ldt116** [kyokomi/gitlab-cli#17]
I got an error when tapping brew with command `brew tap kyokomi/homebrew-gitlab-cli`. It said we need an lib upgrade. Detail as below

```
Invalid formula: /usr/local/Homebrew/Library/Taps/kyokomi/homebrew-gitlab-cli/gitlab-cli.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/kyokomi/homebrew-gitlab-cli/gitlab-cli.rb:10:in `<class:GitlabCli>'
Please report this to the kyokomi/gitlab-cli tap!
```

**Comment by kyokomi** [comment]
@ldt116 Thanks for the report.

https://github.com/kyokomi/homebrew-gitlab-cli/commit/c4cee416d5a87dd60dd87c214adebbeeae326a23
Since we corresponded here, please `brew tap kyokomi/homebrew-gitlab-cli` again.

**Comment by ldt116** [comment]
@kyokomi Thanks you.
